### ISSUE TITLE
[1.0] Remove __set method from AttributeTrait

### ISSUE THREAD

**Issue by stevenmaguire** [JobBrander/jobs-common#14]
I think it might be a bad idea to allow this method to exists moving forward. We've explicitly defined all of the setter methods needed for this library, most of which finesse the data into an appropriate format. We should remove this magic method entirely. 

Thoughts?

**Comment by karllhughes** [comment]
I'm fine with that. Just added explicit setter methods to the javascript calls so they won't be effected by this.

**Comment by stevenmaguire** [comment]
The "setAttributeValue" methods are fine. We don't need to explicitly declare all of those. 

I want to remove the ability to perform the following action:

```php
$job->javascriptAction = 'onclick'; 
```
Removing the __set magic method from the AttributeTrait will take care of that. 

Make sense and sound ok to you?

**Comment by karllhughes** [comment]
Yep, go ahead.

Karl L. Hughes
(901) 827-9637
Google+
<http://t.signauxsept.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3MPbJ0VcW85M2BpySdW1p7ZwM56dzT3f6fjvnj02?t=https%3A%2F%2Fplus.google.com%2F101080316492181821858&si=5634200712511488&pi=0768f074-cfc3-4e9e-db71-ef054b7dfd7f>
| LinkedIn
<http://t.signauxsept.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3MPbJ0VcW85M2BpySdW1p7ZwM56dzT3f6fjvnj02?t=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fkarllhughes&si=5634200712511488&pi=0768f074-cfc3-4e9e-db71-ef054b7dfd7f>
| Twitter
<http://t.signauxsept.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3MPbJ0VcW85M2BpySdW1p7ZwM56dzT3f6fjvnj02?t=http%3A%2F%2Ftwitter.com%2Fkarllhughes&si=5634200712511488&pi=0768f074-cfc3-4e9e-db71-ef054b7dfd7f>
| Web
<http://t.signauxsept.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3MPbJ0VcW85M2BpySdW1p7ZwM56dzT3f6fjvnj02?t=http%3A%2F%2Fkarllhughes.com%2F&si=5634200712511488&pi=0768f074-cfc3-4e9e-db71-ef054b7dfd7f>

**Comment by stevenmaguire** [comment]
Resolved with #16
