### ISSUE TITLE
WTF BBQ! JobPosting on Schema.org just changed its properties

### ISSUE THREAD

**Issue by stevenmaguire** [JobBrander/jobs-common#17]
http://schema.org/JobPosting

[ ] `benefits` is now `jobBenefits`
[ ] `incentives` is now `incentiveCompensation`

I think we should update, and I am not certain how frequently this happens. Thoughts?

**Comment by karllhughes** [comment]
I vote we update too. To be fair it looks like they did just do a major release: http://blog.schema.org/2015/05/schema.html

**Comment by stevenmaguire** [comment]
Good catch on the blog post. We can say we are 2.0 compliant! Are you up for that change?

**Comment by karllhughes** [comment]
Yep, making the change right now!

**Comment by karllhughes** [comment]
We're 2.0 compliant!
