### ISSUE TITLE
Remove salaries and dates, add minimumSalary, maximumSalary, startDate, endDate

### ISSUE THREAD

**Issue by karllhughes** [JobBrander/jobs-common#2]
What do you think about allowing the provider to give custom keys to the Salaries and Dates arrays?

In the case of the Government Jobs API, they give a minimum and maximum pay rate/salary for jobs, and a "start_date" and "end_date". Right now I can add the attributes to the arrays like so:

```
$job->addSalaries($payload['minimum'])
            ->addSalaries($payload['maximum'])
            ->addDates($payload['start_date'])
            ->addDates($payload['end_date']);
```

But then they just show up like this in the job object:

```
                    [dates:protected] => Array
                        (
                            [0] => 2015-04-13
                            [1] => 2015-04-20
                        )

                    [salaries:protected] => Array
                        (
                            [0] => 70192
                            [1] => 118905
                        )
```

Thoughts?

**Comment by stevenmaguire** [comment]
@karllhughes for dates, is it usually just startDate and endDate? Should we just create properties for those? same for salary, is it just minimumSalary and maximumSalary?

**Comment by karllhughes** [comment]
As far as I've seen for dates it's just start and end date, but I wouldn't rule out other possibilities. I suppose we can attack those when they come up.

For salary, min and max would be good, but some vendors give just one salary, so I don't know what the best way to handle that is.

**Comment by stevenmaguire** [comment]
I'd vote for a startDate and endDate singular data attributes. If there is no end date for the job, it will simply be null. 

Same thing for salaries. If there is only one salary, it will be the minimumSalaray; maximumSalary will be null. 

These two opinions will be good to enforce at the core level and will coerce vendor package maintainers to make choices about how their unique data fits the job entity. 

Does that make sense for you?

**Comment by karllhughes** [comment]
Works for me.

Karl L. Hughes
(901) 827-9637
Google+ <https://plus.google.com/101080316492181821858> | LinkedIn
<http://www.linkedin.com/in/karllhughes> | Twitter
<http://twitter.com/karllhughes> | Web <http://karllhughes.com>
