### ISSUE TITLE
Upgrade to Guzzle v.6+

### ISSUE THREAD

**Issue by karllhughes** [JobBrander/jobs-common#26]
I ran a composer update this morning and realized that Guzzle upgraded to version 6. The problem is that this breaks our XML feeds. I didn't spend a lot of time looking into why. My immediate fix was to update the composer.json file to use Guzzle ~5.0.

Should we try to upgrade to Guzzle 6 before our version 1 release or stick with the more stable Guzzle 5? Open to your thoughts @stevenmaguire. Thanks!

**Comment by stevenmaguire** [comment]
Downgrading is great for now. I do think we should look into upgrading though. There are some nice things coming in Guzzle, especially as it relates to PSR7 for Web Messages.

**Comment by karllhughes** [comment]
Upgrade is merged. I'm going to go through all the providers today and make sure they continue to work with the update. I'll probably just have to adjust the tests, so shouldn't be a big deal.
