### ISSUE TITLE
Source Attribute

### ISSUE THREAD

**Issue by karllhughes** [JobBrander/jobs-common#3]
I had originally intended to use the "source" attribute in the job object to indicate which vendor the job came from (eg: Indeed, Government Jobs, Careerbuilder, etc.). Currently it's just showing the company name (which is redundant).

What do you think of making that source the vendor name? It might be useful if comparing collections of jobs from multiple vendors, but I'm open to discussion on it.

**Comment by stevenmaguire** [comment]
I agree completely. If the Indeed library adds the hiring organization to the source attribute, that is a bug. Sorry! Have you noticed this somewhere? I will fix it!

**Comment by karllhughes** [comment]
The indeed library does this:

```
        $job = new Job([
            'title' => $payload['jobtitle'],
            'source' => $payload['source'],
            'dates' => $payload['date'],
            'description' => $payload['snippet'],
            'url' => $payload['url'],
            'id' => $payload['jobkey'],
        ]);
```

I updated the Dice and Govt libraries to set source equal to a protected variable set in the provider. If you have another way of doing it, let me know. Open to ideas.

**Comment by stevenmaguire** [comment]
So Indeed was fine and Dice and Govt needed to be updated? Is this topic closed now?

**Comment by karllhughes** [comment]
Indeed still needs an update I think. Dice and Govt are fine.

Karl L. Hughes
(901) 827-9637
Google+ <https://plus.google.com/101080316492181821858> | LinkedIn
<http://www.linkedin.com/in/karllhughes> | Twitter
<http://twitter.com/karllhughes> | Web <http://karllhughes.com>
