### ISSUE TITLE
[1.0] Codes on Job objects

### ISSUE THREAD

**Issue by stevenmaguire** [JobBrander/jobs-common#5]
Picking up the conversation about how to handle `codes` on job listings:

> This is a place for special codes provided in each job listing. Some providers offer javascript snippets or special ids for their jobs, so it's kind of a catch-all.
@karllhughes from #4 

> is it your observation that codes would contain strings of text that could be executable javascript or miscellaneous strings of identifying data? Is it possible to identify these unique purposes and build for them with intent? One of the benefits of a common base library is that the purpose of each of the methods on the common returned object is decoupled from the vendor supplying the information. If the vendor changes the purpose of the resulting object should not.
@stevenmaguire from #4 

> Codes are very provider dependent. It's probably the least standardized form of data here. Some use names of JS functions, some use unique id's, and some are job codes with unspecified use to the casual observer (probably for internal tools). Since the codes are required to truly implement some of the API's we need to keep them, but they aren't all done the same way and I feel like future providers might add new methods, so keeping codes general is sort of my fall back place for non-standard but necessary data.
@karllhughes from #4

**Comment by karllhughes** [comment]
In the current implementation, I am using the codes array to hold the following data:
- Careerbuilder
  - ONet Code (used in Schema.org for job category - http://schema.org/JobPosting)
  - ONet Title
  - JobLevel (not sure what this means, but might be related to payscale codes)
- Govt Jobs
  - rate_interval_code (payscale code for government use)
- Indeed
  - onmousedown (js function with input params that should be called when link to indeed job is clicked)
- Jobs2Careers
  - onclick - js function w/ input params
- Juju
  - onclick - js function w/ input params
- Simplyhired
  - permalink - non-unique url that is untracked for this job listing

**Comment by karllhughes** [comment]
Here are the changes I propose making for each of these codes:

- Add the following methods to the Job object:
  - setOccupationalCategory($code, $title) -> Helper function sets category text including code and title as requested in the schema.org for JobPosting
  - setJavascriptAction($action) -> Sets an attribute called JavascriptAction that might include something like "onclick" or "onmousedown". These actions are the action to watch for on the HTML link element.
  - setJavascriptFunction($function) -> Function string (with input params) for the js that should be called when the action is performed.

- Attributes to ignore:
  - CareerBuilder/JobLevel
  - Govt/rate_interval_code
  - Simplyhired /permalink

I'm going to implement these in a new branch and will update this issue when finished.
